langchain-ai/helm

- charts/langsmith/templates/backend/api-deployment.yaml
- charts/langsmith/templates/backend/deployment.yaml
- charts/langsmith/templates/frontend/deployment.yaml
- charts/langsmith/templates/hub-backend/api-deployment.yaml
- charts/langsmith/templates/hub-backend/deployment.yaml
- charts/langsmith/templates/playground/deployment.yaml
- charts/langsmith/templates/postgres/stateful-set.yaml
- charts/langsmith/templates/redis/stateful-set.yaml
- charts/langsmith/values.yaml
Some people want to add arbitrary environment variables to pods. This adds support for that
> Add extra env variables support

- charts/langsmith/Chart.yaml
- charts/langsmith/templates/_helpers.tpl
- charts/langsmith/templates/backend/run-migrations.yaml
- charts/langsmith/templates/backend/service-account.yaml
- charts/langsmith/templates/frontend/deployment.yaml
- charts/langsmith/templates/frontend/service-account.yaml
- charts/langsmith/templates/hub-backend/deployment.yaml
- charts/langsmith/templates/hub-backend/service-account.yaml
- charts/langsmith/templates/playground/deployment.yaml
- charts/langsmith/templates/playground/service-account.yaml
- charts/langsmith/templates/postgres/service-account.yaml
- charts/langsmith/templates/postgres/stateful-set.yaml
- charts/langsmith/templates/redis/service-account.yaml
- charts/langsmith/templates/redis/stateful-set.yaml
- charts/langsmith/values.yaml
Add service account support for all our services incase you need to addd extra containers or other permissions. Also fix a few other bugs.
> Add service accounts for all services

- charts/langsmith/Chart.yaml
- charts/langsmith/templates/frontend/config-map.yaml
- charts/langsmith/templates/frontend/deployment.yaml
- charts/langsmith/templates/ingress.yaml
- charts/langsmith/values.yaml
Add support for serving langsmith at a subdomain.
> Add subdomain option to helm

- charts/langsmith/templates/_helpers.tpl
- charts/langsmith/templates/backend/run-migrations.yaml
- charts/langsmith/templates/clickhouse/config-map.yaml
- charts/langsmith/templates/clickhouse/service-account.yaml
- charts/langsmith/templates/clickhouse/service.yaml
- charts/langsmith/templates/clickhouse/stateful-set.yaml
- charts/langsmith/templates/config-map.yaml
- charts/langsmith/values.yaml
Will enable in our backend deployment in a separate pr. This sets up migrations and installs the clickhouse image
> Add Clickhouse stateful set.

- charts/langsmith/templates/backend/deployment.yaml
- charts/langsmith/templates/frontend/deployment.yaml
- charts/langsmith/templates/hub-backend/deployment.yaml
- charts/langsmith/templates/playground/deployment.yaml
- charts/langsmith/templates/queue/deployment.yaml
- charts/langsmith/values.yaml
Use the same parameter name as kubernetes
> Use replicas instead of replica count

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/templates/backend/deployment.yaml
- charts/langsmith/templates/backend/run-migrations.yaml
- charts/langsmith/templates/clickhouse/stateful-set.yaml
Add missing service account names to the appropriate services.
> Fix service account in backend

- charts/langsmith/Chart.yaml
- charts/langsmith/templates/_helpers.tpl
- charts/langsmith/values.yaml
Includes a bunch of misc bug fixes
> fix: release 0.4.4

- charts/langsmith/docs/DELETE-TRACES.md
- charts/langsmith/docs/DELETE-WORKSPACE.md
- charts/langsmith/scripts/delete_trace_by_id.sh
- charts/langsmith/scripts/delete_workspace.sh
Adding two scripts:
- delete trace by ID
- delete workspace by ID
for use in Self-Hosted Environments and docs for the Helm repo.  Will also add docs to the LS doc repo under a separate PR.
> Add deletion scripts and docs for use

- charts/langsmith/docs/DELETE-ORGANIZATION.md
- charts/langsmith/docs/DELETE-TRACES.md
- charts/langsmith/scripts/delete_organization_sh
Add script and docs for removing an entire organization from a self-hosted instance.
> Add SH script to delete an entire organization including all traces and workspaces

- charts/langsmith/docs/RUN-SUPPORT-QUERY-PG.md
- charts/langsmith/scripts/run_support_query_ch.sh
- charts/langsmith/scripts/run_support_query_pg.sh
- charts/langsmith/scripts/support_queries/pg_get_trace_counts_daily.sql
- charts/langsmith/scripts/support_queries/pg_get_trace_counts_monthly.sql
- charts/langsmith/scripts/support_queries/pg_get_trace_counts_weekly.sql
Add script to be called with a file input that runs a query contained within that file and optionally outputs to a csv file.
> Add command to run arbitrary support queries and example queries

- charts/langsmith/docs/RUN-SUPPORT-QUERY-PG.md
Fix copypasta refrence in script name.
> Fix docs copypasta issue

- charts/langsmith/scripts/support_queries/clickhouse/ch_get_pvc_status.sql
Adding support query to the Helm repo for checking the amount of space and free space on the Clickhouse volume.
> Add script for checking status of the pvc

- charts/langsmith/docs/RUN-SUPPORT-QUERY-CH.md
- charts/langsmith/docs/RUN-SUPPORT-QUERY-PG.md
- charts/langsmith/scripts/support_queries/clickhouse/ch_get_current_trace_counts_by_ws_daily.sql
- charts/langsmith/scripts/support_queries/clickhouse/ch_get_current_trace_counts_by_ws_monthly.sql
- charts/langsmith/scripts/support_queries/clickhouse/ch_get_current_trace_counts_by_ws_weekly.sql
- charts/langsmith/scripts/support_queries/clickhouse/ch_get_historic_trace_counts_by_ws_monthly.sql
- charts/langsmith/scripts/support_queries/clickhouse/ch_get_historic_trace_counts_by_ws_weekly.sql
- charts/langsmith/scripts/support_queries/postgres/pg_get_historic_trace_counts_daily.sql
- charts/langsmith/scripts/support_queries/postgres/pg_get_historic_trace_counts_monthly.sql
- charts/langsmith/scripts/support_queries/postgres/pg_get_historic_trace_counts_weekly.sql
- charts/langsmith/scripts/support_queries/postgres/pg_get_users_with_stats.sql
- charts/langsmith/scripts/support_queries/postgres/pg_get_ws_dataset_counts.sql
- charts/langsmith/scripts/support_queries/postgres/pg_get_ws_prompt_counts.sql
Adding a bunch of queries to calculate requested metrics to the support queries folder.
> Add comments to queries describing their use, tweak docs

- charts/langsmith/scripts/support_queries/clickhouse/ch_get_query_exceptions.sql
Add a query to the repository to pull CH query exceptions
> chore: Add query for CH exceptions

- charts/langsmith/examples/medium_size.yaml
Update example to show correct TargetCPUUtilization
> docs: Update Example

- charts/langsmith/README.md
- charts/langsmith/ci/readonly-config-values.yaml
- charts/langsmith/examples/read_only_config.yaml
- charts/langsmith/values.yaml
> docs: add read only examples

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/examples/read_only_config.yaml
- charts/langsmith/templates/backend/auth-bootstrap.yaml
- charts/langsmith/templates/backend/clickhouse-migrations.yaml
- charts/langsmith/templates/backend/deployment.yaml
- charts/langsmith/templates/backend/postgres-migrations.yaml
- charts/langsmith/templates/clickhouse/stateful-set.yaml
- charts/langsmith/templates/frontend/deployment.yaml
- charts/langsmith/templates/platform-backend/deployment.yaml
- charts/langsmith/templates/playground/deployment.yaml
- charts/langsmith/templates/postgres/stateful-set.yaml
- charts/langsmith/templates/queue/deployment.yaml
- charts/langsmith/templates/redis/stateful-set.yaml
- charts/langsmith/values.yaml
> chore: bump versions and add topology spread constraints

- charts/langgraph-cloud/Chart.yaml
- charts/langgraph-cloud/README.md
- charts/langgraph-cloud/templates/api-server/deployment.yaml
> fix: use service account name

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/templates/frontend/config-map.yaml
Fix incorrect rewrite for /v1/platform routes when specifying a baseURl
> fix: support correct platform rewrite when specifying a base url

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/values.yaml
Fix is in 0.9.69 application version, not 0.9.68
> fix: bump application version for Azure dataset deletion fix

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
https://github.com/langchain-ai/helm/pull/272 didn't bump chart version so there was no release
> fix: bump chart version

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/templates/operator/config-map.yaml
- charts/langsmith/templates/operator/crds.yaml
- charts/langsmith/templates/operator/deployment.yaml
- charts/langsmith/templates/operator/rbac.yaml
- charts/langsmith/values.yaml
Most changes are from CRD manifest additions.
> chore: bump langsmith 0.10.52

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/values.yaml
> chore: bump 0.10.23

- charts/langsmith/scripts/mirror_langsmith_images.sh
> chore: add mirroring images script

- charts/langsmith/templates/ace-backend/hpa.yaml
- charts/langsmith/templates/backend/hpa.yaml
- charts/langsmith/templates/frontend/hpa.yaml
- charts/langsmith/templates/platform-backend/hpa.yaml
- charts/langsmith/templates/playground/hpa.yaml
- charts/langsmith/templates/queue/hpa.yaml
I'd like to add custom metrics for HPA. I think it could be useful when we have to consider lots of situations.
> Add HPA addtional custom metrics

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/templates/frontend/config-map.yaml
> fix: fix routing to use prefixes instead of regex

- charts/langgraph-dataplane/Chart.yaml
- charts/langgraph-dataplane/values.yaml
- charts/langsmith/Chart.yaml
- charts/langsmith/values.yaml
In some envs this is very slow so bump the timeout.
> chore: bump queue start timeouts

- charts/langsmith/Chart.yaml
- charts/langsmith/templates/frontend/config-map.yaml
- charts/langsmith/templates/host-backend/deployment.yaml
Host Backend docs currently not working when hit through ingress, returning "not found"
> fix: add host-backend docs to Nginx configuration

- charts/langgraph-dataplane/Chart.yaml
- charts/langgraph-dataplane/README.md
- charts/langgraph-dataplane/templates/operator/rbac.yaml
- charts/langsmith/README.md
Properly handle namespace field when in an iteration.
> chore: fix namespace in dataplane chart

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/values.yaml
Can cause a panic on some redis commands.
> fix: revert telemetry change

- .github/workflows/release_charts.yaml
- charts/langsmith/Chart.yaml
- charts/langsmith/templates/backend/clickhouse-migrations.yaml
- charts/langsmith/templates/backend/postgres-migrations.yaml
Push against an old stable branch
> chore: bump 0.8.29

- charts/langgraph-dataplane/Chart.yaml
- charts/langgraph-dataplane/values.yaml
- charts/langsmith/Chart.yaml
- charts/langsmith/values.yaml
Fixes using v2 api database with database enabled flag.
> chore: bump helm 0.11.32

- charts/langgraph-dataplane/Chart.yaml
- charts/langgraph-dataplane/README.md
- charts/langgraph-dataplane/templates/ingress.yaml
test plan: run helm installation in eks cluster with metricsPrefix set
> fix: treat metrics prefix as bool in ingress template

- charts/langgraph-dataplane/Chart.yaml
- charts/langgraph-dataplane/templates/listener/rbac.yaml
- charts/langgraph-dataplane/templates/listener/service-account.yaml
- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/templates/ace-backend/service-account.yaml
- charts/langsmith/templates/backend/service-account.yaml
- charts/langsmith/templates/clickhouse/service-account.yaml
- charts/langsmith/templates/e2e-test/service-account.yaml
- charts/langsmith/templates/frontend/service-account.yaml
- charts/langsmith/templates/host-backend/service-account.yaml
- charts/langsmith/templates/listener/rbac.yaml
- charts/langsmith/templates/listener/service-account.yaml
- charts/langsmith/templates/operator/service-account.yaml
- charts/langsmith/templates/platform-backend/service-account.yaml
- charts/langsmith/templates/playground/service-account.yaml
- charts/langsmith/templates/postgres/service-account.yaml
- charts/langsmith/templates/queue/service-account.yaml
- charts/langsmith/templates/redis/service-account.yaml
Some envs require this permission.
Closes Issue-453
> fix: fix rbac for listener
