langchain-ai/helm

- charts/langsmith/templates/frontend/config-map.yaml
- charts/langsmith/values.yaml
Ad the option to enable an oai cache on your langsmith instance.
> feat: Add oai cache to our frontend container

- charts/langsmith/templates/_helpers.tpl
- charts/langsmith/values.yaml
```
config:
ttl:
enabled: true
upgrade_enabled: true
ttl_period_seconds:
longlived: <ll_seconds>
shortlived: <sl_seconds>
```
To set:
```
- name: FF_TRACE_TIERS_ENABLED
value: "true"
- name: FF_UPGRADE_TRACE_TIER_ENABLED
value: "true"
- name: TRACE_TIER_TTL_DURATION_SEC_MAP
value: "{ \"longlived\": 1234, \"shortlived\": 567 }"
```
> Add options for TTL

- charts/langsmith/templates/_helpers.tpl
- charts/langsmith/templates/secrets.yaml
- charts/langsmith/values.yaml
Add the ability to configure s3 using access key/secret. Workload identity support coming soon
> fix: add blobstorage config

- charts/langsmith/scripts/support_queries/clickhouse/ch_get_query_stats_hourly.sql
Adds a query to the support queries folder that gets us per-query stats from Clickhouse by the hour.
> Add query for per-ls-query stats

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/templates/_helpers.tpl
- charts/langsmith/templates/backend/auth-bootstrap.yaml
- charts/langsmith/templates/backend/clickhouse-migrations.yaml
- charts/langsmith/templates/backend/deployment.yaml
- charts/langsmith/templates/backend/postgres-migrations.yaml
- charts/langsmith/templates/clickhouse/stateful-set.yaml
- charts/langsmith/templates/config-map.yaml
- charts/langsmith/templates/frontend/deployment.yaml
- charts/langsmith/templates/platform-backend/deployment.yaml
- charts/langsmith/templates/playground/deployment.yaml
- charts/langsmith/templates/postgres/stateful-set.yaml
- charts/langsmith/templates/queue/deployment.yaml
- charts/langsmith/templates/redis/stateful-set.yaml
duplicate env vars cause strange behavior with Helm: https://github.com/fluxcd/helm-controller/issues/539. this can result in removing environment variables accidentally.
this change adds checks to fail fast if duplicate environment variables are detected in the `langsmith` chart
> feat: prevent duplicate env var keys

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/templates/_helpers.tpl
- charts/langsmith/templates/config-map.yaml
- charts/langsmith/values.yaml
* this release includes a change from using cookies for session storage to using Redis (for OAuth with Client Secret).
related: https://github.com/markbates/goth/issues/133
* also includes a fix to add common env vars to the `config-map` since `commonEnv` isn't used for all services (e.g. not `ace-backend`)
> chore: bump version for large sessions w/ oauth with client secret

- .github/workflows/helm_checks.yaml
- charts/langsmith/.helmignore
- charts/langsmith/templates/_helpers.tpl
- charts/langsmith/tests/langsmith_hybrid_test.yaml
- charts/langsmith/tests/values/blob-storage-defaults-enabled.yaml
- charts/langsmith/values.yaml
* install and use https://github.com/helm-unittest/helm-unittest in CI
* run a test to confirm hybrid ClickHouse params for both default `Values` (disabled) and when enabled
> ci: add helm-unittest & test hybrid params

- charts/langsmith/Chart.yaml
- charts/langsmith/values.yaml
https://docs.smith.langchain.com/self_hosting/organization_charts
> chore: bump version for org-scoped usage charts

- charts/langgraph-cloud/README.md
- charts/langgraph-cloud/templates/api-server/deployment.yaml
- charts/langgraph-cloud/values.yaml
I would like to be able to add configMapRef or secretRef objects to the langgraph apiServer.
Create a test values file (`test-values.yaml`) with the following content:
```yaml
images:
apiServerImage:
repository: "docker.io/langchain/langgraph-api"
pullPolicy: Always
tag: "3.11"
config:
langGraphCloudLicenseKey: "test-license"
apiServer:
deployment:
envFrom:
- configMapRef:
name: test-configmap
- secretRef:
name: test-secret
```
Run the following command to generate the manifest and verify the envFrom configuration:
```bash
helm template langgraph-cloud charts/langgraph-cloud -f test-values.yaml | grep -A 10 "envFrom:"
```
Expected output:
```yaml
envFrom:
- configMapRef:
name: test-configmap
- secretRef:
name: test-secret
```
This verifies that:
- The envFrom template in the …
> feat: add envFrom to apiServer

- charts/langsmith/Chart.yaml
- charts/langsmith/values.yaml
removes `backend` startup ping to cloud storage
> chore: bump version for blob storage fix

- charts/langgraph-dataplane/Chart.yaml
- charts/langgraph-dataplane/templates/_helpers.tpl
- charts/langgraph-dataplane/templates/listener/deployment.yaml
- charts/langgraph-dataplane/templates/listener/pdb.yaml
- charts/langgraph-dataplane/templates/operator/deployment.yaml
- charts/langgraph-dataplane/templates/operator/pdb.yaml
This label is already hard-coded in the deployment templates, it's causing duplication issues when we template the chart with kustomize. LMK if you need more info
> Update app.kubernetes.io labels to be consistent across templates

- charts/langsmith/README.md
- charts/langsmith/values.yaml
**Summary** Refine Redis TTL to 6 hours, which after discussing with Alex and Mukil could be a balances between disaster recovery and redis mem+cpu load.
**Issue**: With a 12 hour redis TTL, 12 hour of throughput (mostly traces) will almost always be stored in redis. In case of  trace ingestion at rate of QPS 10 ~ 100 qps without object storage enabled, each hour has 2GB+ data throughput and 12hour means 24GB+ of redis memory (for small redis this means Memory is always be full and high eviction will happen causing cpu load go up and latency increase). This issue was noticed in a big langsmith self-hosted customer for exact same reason.
** Fix** Simple fix is reduce to 6 hour, which should be still enough buffer time if consumer ( clickhouse etc) down but make redis 50% less stressful in …
> Finetune Redis TTL: reduce from 12hr to 6

- charts/langsmith/docker-compose/.env.example
- charts/langsmith/templates/backend/auth-bootstrap.yaml
Test plan:
With password: `interVieww123`
Error on helm install:
```
joaquinborggio@Joaquin-Borggio-MacBook-ProF67FV2QWH5 helm % helm upgrade -i -f curr_smith_values.yaml langsmith charts/langsmith
Error: UPGRADE FAILED: execution error at (langsmith/templates/backend/auth-bootstrap.yaml:14:6): Error: Admin password must contain at least one symbol from: !#$%()+,-./:?@[\]^_{~}
``` 
With password: `interview`
Error on helm install:
```
joaquinborggio@Joaquin-Borggio-MacBook-ProF67FV2QWH5 helm % helm upgrade -i -f curr_smith_values.yaml langsmith charts/langsmith
Error: UPGRADE FAILED: execution error at (langsmith/templates/backend/auth-bootstrap.yaml:5:6): Error: Admin password must be at least 12 characters long
```
With password: `interviewwwwwwww`
Error on helm install:
``` …
```
> test: Validate admin password in the helm template during install

- charts/langsmith/scripts/get_k8s_debugging_info.sh
Here we add a script to help pull important kubernetes info for debugging langsmith.
Usage example:
`bash get_k8s_debugging_info.sh --namespace langsmith`
What this script pulls for the namespace passed in as an argument:
- A wide summary view of all resources
- A detailed yaml view of all resources
- Kubernetes events
- Resource usage for all containers within every pod in the namespace
- All container logs from the last 24 hours
- For containers that have restarted, we pull the previous container logs
Next step: Add a link to this in our troubleshooting page: https://docs.smith.langchain.com/self_hosting/troubleshooting
Testing:
I ran this on a cluster and got this:
```
% bash charts/langsmith/scripts/get_k8s_debugging_info.sh --namespace interview
Starting to pull debugging info. …
```
> feat: Add a script to help pull important kubernetes info for debugging

- charts/langsmith/examples/read_only_config.yaml
Make the templates we deploy readonly as well.
> chore: add lgp control plane templates to read only config

- charts/langgraph-cloud/Chart.yaml
- charts/langgraph-cloud/templates/queue/deployment.yaml
- charts/langgraph-cloud/values.yaml
This change adds support for envFrom configuration in the queue deployment template, allowing users to reference ConfigMaps and Secrets as environment variable sources.
> Add envFrom support to queue deployment

- charts/langsmith/values.yaml
Startup probe default timeout is a bit short. Some clusters see this command take roughly 40 seconds. Bumping default timeout here.
> fix: bump default timeout of queue startup probe

- charts/langgraph-cloud/templates/api-server/deployment.yaml
- charts/langgraph-cloud/templates/postgres/stateful-set.yaml
- charts/langgraph-cloud/templates/queue/deployment.yaml
- charts/langgraph-cloud/templates/redis/deployment.yaml
- charts/langgraph-cloud/templates/studio/deployment.yaml
- charts/langgraph-cloud/values.yaml
- charts/langgraph-dataplane/templates/listener/deployment.yaml
- charts/langgraph-dataplane/templates/operator/deployment.yaml
- charts/langgraph-dataplane/templates/redis/stateful-set.yaml
- charts/langgraph-dataplane/values.yaml
- charts/langsmith/templates/backend/deployment.yaml
- charts/langsmith/templates/clickhouse/stateful-set.yaml
- charts/langsmith/templates/e2e-test/job.yaml
- charts/langsmith/templates/frontend/deployment.yaml
- charts/langsmith/templates/host-backend/deployment.yaml
- charts/langsmith/templates/listener/deployment.yaml
- charts/langsmith/templates/operator/deployment.yaml
- charts/langsmith/templates/platform-backend/deployment.yaml
- charts/langsmith/templates/postgres/stateful-set.yaml
- charts/langsmith/templates/queue/deployment.yaml
- charts/langsmith/templates/redis/stateful-set.yaml
- charts/langsmith/values.yaml
(All except playground and ace-backend since they are sandboxed)
> chore: Add commonVolumes and commonVolumeMounts to all deployments

- charts/langsmith/templates/e2e-test/job.yaml
Let's run the e2e test post upgrade as well as post install. If someone installs with `--wait`, then e2e failures will raise a message that something is wrong.
> chore: run e2e test post upgrade

- charts/langsmith/values.yaml
Deployed internally to ensure we could handle at least 10 RPS on the read side
> chore: bump default backend replicas

- charts/langsmith/README.md
- charts/langsmith/values.yaml
Bump the default timeout for probes on the backend service from 1s to 10s.
Normally 1s is fine when the cluster is not under high load. Under high load some requets to stateful services can take longer and so the health check needs more time.
During load testing, backend pods would crash bc of timeouts on the probes constantly. When bumping timeout to 10s, I didnt see any more restarts.
> chore: bump default backend probe timeouts (for high load)

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/values.yaml
adds feature flag that controls trace tier precedence for runs ingested via `platform-backend`. previously, org-scoped trace tier settings would override workspace-scoped. when the feature flag is on, workspace-scoped will override org-scoped.
> chore: bump version for trace tier precedence update

- charts/langgraph-dataplane/Chart.yaml
- charts/langgraph-dataplane/README.md
- charts/langgraph-dataplane/templates/ingress.yaml
- charts/langgraph-dataplane/templates/listener/config-map.yaml
- charts/langgraph-dataplane/templates/listener/deployment.yaml
- charts/langgraph-dataplane/templates/listener/hpa.yaml
- charts/langgraph-dataplane/templates/listener/pdb.yaml
- charts/langgraph-dataplane/templates/listener/rbac.yaml
- charts/langgraph-dataplane/templates/listener/service-account.yaml
- charts/langgraph-dataplane/templates/operator/config-map.yaml
- charts/langgraph-dataplane/templates/operator/deployment.yaml
- charts/langgraph-dataplane/templates/operator/pdb.yaml
- charts/langgraph-dataplane/templates/operator/rbac.yaml
- charts/langgraph-dataplane/templates/operator/service-account.yaml
- charts/langgraph-dataplane/templates/operator/service.yaml
- charts/langgraph-dataplane/templates/redis/pdb.yaml
- charts/langgraph-dataplane/templates/redis/secrets.yaml
- charts/langgraph-dataplane/templates/redis/service-account.yaml
- charts/langgraph-dataplane/templates/redis/service.yaml
- charts/langgraph-dataplane/templates/redis/stateful-set.yaml
- charts/langgraph-dataplane/templates/secrets.yaml
Fixes incorrect namespace for certain rolebindings. Also standardizes on not adding extra quote to string variables.
Closes INF-698
> fix: use correct namespace everywhere for langgraph-dataplane chart

- charts/langgraph-cloud/Chart.yaml
- charts/langgraph-cloud/templates/api-server/deployment.yaml
- charts/langgraph-cloud/templates/queue/deployment.yaml
- charts/langgraph-cloud/templates/studio/deployment.yaml
- charts/langgraph-cloud/values.yaml
Add configurable startupProbe, readinessProbe, and livenessProbe settings to apiServer.deployment in values.yaml. This allows users to customize probe settings while maintaining existing defaults.
Changes:
- Add probe configurations to values.yaml with current defaults
- Update deployment.yaml to use values from values.yaml
- Maintains backward compatibility with existing behavior
Why:
- Slow liveness/readiness healthchecks are causing application pods to restart frequently
- We want to make liveness/readiness `httpGet` checks instead of exec, and update some of the time settings for each of the probe types.
> feat: make api-server probes configurable via values.yaml

- charts/langsmith/README.md
- charts/langsmith/values.yaml
Disable randomizing name by default. This is only useful when running via helm template.
> chore: disable randomize name by default

- charts/langsmith/templates/backend/auth-bootstrap.yaml
Currently, if using oauth and you don't bind initial_org_admin_password in your secret (not needed for oauth), container fails to come up due to CreateContainerConfigError
> Fix: Only bind password to auth bootstrap job if Basic Auth enabled

- charts/langsmith/scripts/get_k8s_debugging_info.sh
- Updates `get_k8s_debugging_info.sh` to filter results for only LangChain-related resources
- Allows customers to embed other resources in the same cluster without polluting debug output
- Removes `jq` dependency by using `jsonpath` for restart count check
- **Resource filtering**: Added grep filters for `langsmith-*`, `lg-*`, and `toolbox*` prefixes to:
- Resource summary output
- Resource details YAML
- Pod resource usage
- Pod log collection
- **Simplified restart count check**: Changed from `jq` to `jsonpath` for better portability
- **Improved output messages**: Updated echo statements for clarity
> chore: filter K8s debugging script to LangChain resources only

- charts/langsmith/Chart.yaml
- charts/langsmith/README.md
- charts/langsmith/ci/readonly-config-values.yaml
- charts/langsmith/examples/read_only_config.yaml
- charts/langsmith/templates/ace-backend/deployment.yaml
- charts/langsmith/templates/frontend/deployment.yaml
- charts/langsmith/values.yaml
Testing
Confirmed that without the volume mounts you get a validation error with readonly:
```
Error: INSTALLATION FAILED: execution error at (langsmith/templates/frontend/deployment.yaml:46:4): ERROR: When frontend.deployment.securityContext.readOnlyRootFilesystem is true, you must mount both /var/lib/nginx and /var/run as writable volumes. Add emptyDir volumes for 'var-lib-nginx' mounted at /var/lib/nginx and 'var-run' mounted at /var/run. See read_only config example.
```
Once you add volume mounts the error goes away.
Confirmed that without the ace volume you also get an error:
```
Error: INSTALLATION FAILED: execution error at (langsmith/templates/ace-backend/deployment.yaml:18:4): ERROR: When aceBackend.deployment.securityContext.readOnlyRootFilesystem is true, you must mount …
```
> chore: release new wolfi images with validation
